name: Bug Report
description: Report a feature that is not working as expected.
labels: [bug]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of the issue.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to illustrate your issue.
    validations:
      required: false
  - type: input
    id: resonite-version
    attributes:
      label: Resonite Version (include branch if on any)
      placeholder: 2025.9.12.1173
    validations:
      required: true
  - type: input
    id: rml-version
    attributes:
      label: ResoniteModLoader Version
      placeholder: 4.0.0
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: What Platforms does this occur on?
      multiple: true
      options:
        - "Windows"
        - "Linux"
        - "Other"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log files
      description: Please provide a log file that replicates the issue. Logs can be found in the install directory, for more info read the [resonite wiki](https://wiki.resonite.com/Log_files).
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
