using System.Globalization;
using Elements.Core;
using FrooxEngine;

namespace ResoniteModLoader;

/// <summary>
/// Settings UI for the mod loader itself.
/// </summary>
[AutoRegisterSetting]
[SettingCategory("ResoniteModLoader")]
public sealed class ModLoaderSettings : SettingComponent<ModLoaderSettings> {
	/// <inheritdoc/>
	public override bool UserspaceOnly => true;

#pragma warning disable CS8618 // Initializer generated by Resonite

	/// <summary>How count of loaded mods.</summary>
	[SettingIndicatorProperty]
	public readonly RawOutput<string> LoadedMods;

	/// <summary>The version of RML. Corresponds to <see cref="ModLoader.VERSION"/>.</summary>
	[SettingIndicatorProperty]
	public readonly RawOutput<string> ModLoaderVersion;

	/// <summary>Corresponds to <see cref="ModLoaderConfiguration.Debug"/>.</summary>
	[SettingProperty]
	public readonly Sync<bool> DebugMode;

	/// <summary>Corresponds to <see cref="ModLoaderConfiguration.HideVisuals"/>.</summary>
	[SettingProperty]
	public readonly Sync<bool> HideVisuals;

	/// <summary>
	/// Link to the RML GitHub repository at https://github.com/resonite-modding-group/ResoniteModLoader.
	/// </summary>
	//TODO make clickable link in UI
	[SettingIndicatorProperty]
	public readonly RawOutput<string> ProjectLink;

#pragma warning restore CS8618

	/// <summary>
	/// Since the Project Link indicator is not clickable,
	/// this button provides this functionality instead.
	/// </summary>
	[SettingProperty("Open Github Repo", "")]
	[SyncMethod(typeof(Action), [])]
	public void OpenGithubRepo() {
		Userspace.UserspaceWorld.RunSynchronously(delegate {
			Slot slot = Userspace.UserspaceWorld.AddSlot("Hyperlink", false);
			slot.PositionInFrontOfUser(new float3?(float3.Backward));
			slot.AttachComponent<HyperlinkOpenDialog>().Setup(new(ProjectLink.Value), "");
		});
	}
	/// <inheritdoc/>
	public override void ResetToDefault() {
		DebugMode.Value = false;
		HideVisuals.Value = false;
	}

	/// <inheritdoc/>
	protected override void OnChanges() {
		base.OnChanges();
		ModLoaderConfiguration.Get().Debug = DebugMode.Value;
		Logger.DebugInternal($"Setting changed, changed debug values {ModLoaderConfiguration.Get().Debug}");

		ModLoaderVersion.Value = ModLoader.VERSION;
		LoadedMods.Value = ModLoader.Mods().Count().ToString(CultureInfo.InvariantCulture);
	}

	/// <inheritdoc/>
	protected override void OnStart() {
		base.OnStart();
		ModLoaderVersion.Value = ModLoader.VERSION;
		LoadedMods.Value = ModLoader.Mods().Count().ToString(CultureInfo.InvariantCulture);
		DebugMode.Value = ModLoaderConfiguration.Get().Debug;
		HideVisuals.Value = ModLoaderConfiguration.Get().HideVisuals;
		ProjectLink.Value = "https://github.com/resonite-modding-group/ResoniteModLoader";
	}
}
